### ISSUE TITLE
Forbidden (403) error when going to index page https://osu.kiwec.net/

### ISSUE THREAD

**Issue by coozieki** [kiwec/osu-ranked-lobbies#14]
![image](https://user-images.githubusercontent.com/69788536/146630520-8eee1e41-fc3a-45a0-8ced-90600ebf33ce.png)

@kiwec so for some reason i can't access the index page of the website, although it works fine in my dev environment and redirects to leaderboards page

**Comment by kiwec** [comment]
Fixed, it was a nginx configuration mistake.
