### ISSUE TITLE
Handle passworded lobbies

### ISSUE THREAD

**Issue by kiwec** [kiwec/osu-ranked-lobbies#19]
Referees can set a lobby password with `!mp password`. This makes the lobby unjoinable, but it still appears in #lobbies.

Possible fixes:
- Hide passworded lobbies from #lobbies
- Store password, add it to invite link (not handled by bancho.js, so would need to track referees and parse the `!mp password` command)
- Remove password when password is set (easiest solution)

**Comment by coozieki** [comment]
> * Store password, add it to invite link (not handled by bancho.js, so would need to track referees and parse the `!mp password` command)

But if referee has set password then this means he wants only certain people to join his lobby i think, otherwise why would he set password lol.
I think passworded lobbies can lead to abusing the rating system with friends? If it's possible. So maybe best solution is just removing the password

**Comment by kiwec** [comment]
Fixed in https://github.com/kiwec/osu-ranked-lobbies/commit/a999b1f419d6e769e6c214f0cbb6023fa5a7286f
