### ISSUE TITLE
Losing elo without playing the map

### ISSUE THREAD

**Issue by coozieki** [kiwec/osu-ranked-lobbies#32]
![image](https://user-images.githubusercontent.com/69788536/147388394-c20dc7b6-c9a7-4ca8-a65b-491aef439c3c.png)

I joined the lobbies **after** the game has already started to check if !rank was working fine and i left before the game was finished. And it counted as if I played the map and placed last. Lost 900 elo :(

**Comment by kiwec** [comment]
Fixed in https://github.com/kiwec/osu-ranked-lobbies/commit/0252c42a06991e66131026271dd6acfe926e7d0b
