### ISSUE TITLE
Change new_map query

### ISSUE THREAD

**Issue by coozieki** [kiwec/osu-ranked-lobbies#34]
These are the amount of maps for different length ranges i got by searching in maps.db
```
>=210 <=240 6385
>=180 <=210 8311
>=150 <=180 9154
>=120 <=150 9840
>=90  <=120 17249
>=60  <=90  25680
```
As you can see there are 25680 1:00-1:30 maps while there are only 23850 2:30-4:00 maps.
IMO it would be better if we took an equal amount of maps from all the different length ranges like 1:00-2:00, 2:00-3:00 and 3:00-4:00 (and maybe a bit less for >4:00, but i am not sure if playing such long maps in multi is reasonable). So tv size maps would not be picked so often as it is right now.

I made an example query which can probably solve this:
```SQL
SELECT * FROM (
  SELECT *, pp.stars AS pp_stars, (
    ABS(${lobby.median_aim} - aim_pp)
    + ABS(${lobby.median_speed} - speed_pp)
    + ABS(${lobby.median_acc} - acc_pp)
    + 10*ABS(${lobby.median_ar} - pp.ar)
  ) AS match_accuracy FROM map
  INNER JOIN pp ON map.id = pp.map_id
  WHERE match_accuracy IS NOT NULL
  AND (
    id IN (
      SELECT id FROM map
      WHERE length >= 60
      AND length <= 120
      AND pp.stars >= ${lobby.min_stars} 
      AND pp.stars <= ${lobby.max_stars}
      AND mods = (1<<16)
      AND dmca = 0
      AND ranked IN (4, 5, 7)
      ORDER BY RANDOM()
      LIMIT 333
    )
    OR id IN (
      SELECT id FROM map
      WHERE length >= 120
      AND length <= 180
      AND pp.stars >= ${lobby.min_stars} 
      AND pp.stars <= ${lobby.max_stars}
      AND mods = (1<<16)
      AND dmca = 0
      AND ranked IN (4, 5, 7)
      ORDER BY RANDOM()
      LIMIT 333
    )
    OR id IN (
      SELECT id FROM map
      WHERE length >= 180
      AND length <= 240
      AND pp.stars >= ${lobby.min_stars} 
      AND pp.stars <= ${lobby.max_stars}
      AND mods = (1<<16)
      AND dmca = 0
      AND ranked IN (4, 5, 7)
      ORDER BY RANDOM()
      LIMIT 333
    )
    OR id IN (
      SELECT id FROM map
      WHERE length >= 240
      AND pp.stars >= ${lobby.min_stars} 
      AND pp.stars <= ${lobby.max_stars}
      AND mods = (1<<16)
      AND dmca = 0
      AND ranked IN (4, 5, 7)
      ORDER BY RANDOM()
      LIMIT 100
    )
  )
  ORDER BY match_accuracy LIMIT 500
) 
ORDER BY RANDOM() LIMIT 1`,
```

So as you can see we take maximum 
- 333 of 1:00-2:00
- 333 of 2:00-3:00 
- 333 of 3:00-4:00 and 
- 100 of 4:00-+∞ maps. 

The maps are picked randomly in these subqueries, not depending on match_accuracy so instead we can just `ORDER BY match_accuracy LIMIT 500` and limit these 1100 maps to 500 (maybe even less) to make the selection more accurate for current match_accuracy

**Comment by coozieki** [comment]
Related to #7

**Comment by coozieki** [comment]
Should JOIN pp table in each subquery to get the pp.stars, forgot about that. I didn't test the time complexity of this query, but I think in case it's too slow, you can just search for new map after the current game started and not after it finished, so you would have enough time.

**Comment by kiwec** [comment]
Instead of making a huge query, you could randomly choose the length filters with `Math.random()` before making the query, and pass the filters.

60-120 is a good range for TV size, a lot of maps are 91 seconds.

|    | 1-2min | 2-3min | 3-4min | 4min+ |
|------|--------|--------|--------|-------|
| **3-4*** | 9241   | 4405   | 3469   | 700   |
| **4-5*** | 7553   | 2811   | 2625   | 1488  |
| **5-6*** | 4666   | 1692   | 2008   | 1722  |

It's hard to tell how many maps would actually get picked with the average pp filters, though. We could always stop using those in lobbies with fixed star range, and make it random instead.

**Comment by kiwec** [comment]
Map length distribution

![2022-01-05-000906_417x268_scrot](https://user-images.githubusercontent.com/1957540/148136378-679988fe-456a-4dc3-89a1-7cd9f6542961.png)
![2022-01-05-001107_421x261_scrot](https://user-images.githubusercontent.com/1957540/148136379-cf22c017-496b-42ef-b3ee-b9ae535d2a96.png)

**Comment by kiwec** [comment]
it's gonna change
