### ISSUE TITLE
/api/lobbies/ is empty

### ISSUE THREAD

**Issue by kiwec** [kiwec/osu-ranked-lobbies#60]
https://osu.kiwec.net/api/lobbies/ returns [] despite many lobbies being open (with end_time == NULL)

**Comment by DLi7077** [comment]
looks like it's fixed
![image](https://user-images.githubusercontent.com/51217000/196006317-3845bf62-5111-4edf-8120-4c7cd08b6c49.png)

**Comment by kiwec** [comment]
Seems to be fixed
